name: lji
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter: 
    sdk: flutter
  curved_navigation_bar: ^1.0.3
  intl: ^0.19.0
  


dev_dependencies:
  flutter_test:
    sdk: flutter    
  flutter_lints: ^3.0.1
  google_fonts: ^6.1.0

flutter:
  assets:
    - assets/Logoes.png
    - assets/menu1.png
    - assets/menu2.png
    - assets/notif.png
    - assets/log.png
    - assets/keranjang.png
    - assets/buttonkeranjang.png
    - assets/search.png
    - assets/makan.png
    - assets/minum.png
    - assets/produk.png
    - assets/stok.png
    - assets/teh taro.jpg
    - assets/uang.png
    - assets/minum_black.png
    - assets/makan_white.png
    - assets/stok_white.png


    

  uses-material-design: true
  
    